## Logistic Regression

In [44]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,confusion_matrix, ConfusionMatrixDisplay
from scipy.stats.mstats import winsorize

### Data Cleaning and Exploration

In [45]:
# adding column names to dataframe
col_names = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15"]

df = pd.read_csv(r"C:\Users\DELL\Desktop\ML\Datasets\credit_approval\crx.data", header = None, na_values = "?")
df.columns = col_names + ["Target"]

In [46]:
df.head()

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15 Target
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202.0    0      +
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43.0  560      +
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  280.0  824      +
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100.0    3      +
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120.0    0      +

In [47]:
df.shape

(690, 16)

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
df = df.drop_duplicates()

In [50]:
df.isna().sum()

A1        12
A2        12
A3         0
A4         6
A5         6
A6         9
A7         9
A8         0
A9         0
A10        0
A11        0
A12        0
A13        0
A14       13
A15        0
Target     0
dtype: int64

In [51]:
for col in df.select_dtypes("object").columns:
    u = df[col].unique()
    print(u)

['b' 'a' nan]
['u' 'y' nan 'l']
['g' 'p' nan 'gg']
['w' 'q' 'm' 'r' 'cc' 'k' 'c' 'd' 'x' 'i' 'e' 'aa' 'ff' 'j' nan]
['v' 'h' 'bb' 'ff' 'j' 'z' nan 'o' 'dd' 'n']
['t' 'f']
['t' 'f']
['f' 't']
['g' 's' 'p']
['+' '-']

In [52]:
#check fr symmetry

for col in df.select_dtypes("number").columns:
    sns.histplot(df[col], kde = True)
    print()
    plt.show()

C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\2771072474.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\2771072474.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\2771072474.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\2771072474.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\2771072474.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\2771072474.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [53]:
#check for outliers

for col in df.select_dtypes("number").columns:
    sns.boxplot(df[col], orient = "h")
    plt.show()

C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\476256638.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\476256638.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\476256638.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\476256638.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\476256638.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\476256638.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [54]:
# fill missing numeric columns with their respective median
for col in df.select_dtypes("number").columns:
    df[col] = df[col].fillna(df[col].median())

In [55]:
# fill missing categorical columns with their respective mode

for col in df.select_dtypes("object").columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [56]:
# check for confirmation

df.isna().sum()

A1        0
A2        0
A3        0
A4        0
A5        0
A6        0
A7        0
A8        0
A9        0
A10       0
A11       0
A12       0
A13       0
A14       0
A15       0
Target    0
dtype: int64

In [57]:
# remove/reduce outliers

for col in df.select_dtypes("number").columns:
    df[col] =  winsorize(df[col], limits = [0.1, 0.1])

In [82]:
for col in df.select_dtypes("number").columns:
    sns.boxplot(df[col], orient = "h")
    plt.show()

C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\DELL\AppData\Local\Temp\ipykernel_15264\1807677673.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

#### Data Encoding and Scaling

In [59]:

le = LabelEncoder()
ss = StandardScaler()

for col in df.columns:
    df[col] = le.fit_transform(df[col])

In [60]:
df.head()

   A1   A2  A3  A4  A5  A6  A7  A8  A9  A10  A11  A12  A13  A14  A15  Target
0   1  122   0   1   0  12   7  30   1    1    1    0    0   68    0       0
1   0  251  81   1   0  10   3  65   1    1    6    0    0   11  119       0
2   0   54   4   1   0  10   3  36   1    0    0    0    0   96  140       0
3   1   90  34   1   0  12   7  73   1    1    5    1    0   31    3       0
4   1    8  97   1   0  12   7  41   1    0    0    0    2   37    0       0

##### Data Split

In [61]:
X = df.drop(columns = "Target")
y = df["Target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(552, 15) (138, 15) (552,) (138,)

In [62]:
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

### Model Building and Evaluation

In [63]:
model = LogisticRegression(max_iter = 10000)

model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=10000)

##### Model testing

In [64]:
y_train_pred = model.predict(X_train_scaled)

##### Evaluation

In [65]:
accuracy = accuracy_score(y_train, y_train_pred)
print(f"accuracy : {accuracy:.2f}")

accuracy : 0.87

In [66]:
precision = precision_score(y_train, y_train_pred)

print(f"precision : {precision:.2f}")

precision : 0.91

In [67]:
recall = recall_score(y_train, y_train_pred)

print(f"recall : {recall:.2f}")

recall : 0.86

In [68]:
f1_score = f1_score(y_train, y_train_pred)

print(f"f1_score : {f1_score:.2f}")

f1_score : 0.89

In [69]:
roc_auc = roc_auc_score(y_train, y_train_pred)

print(f"roc_auc : {roc_auc:.2f}")

roc_auc : 0.88

In [70]:
cm = confusion_matrix(y_train, y_train_pred)
matrix = ConfusionMatrixDisplay(cm, display_labels = model.classes_ )
matrix.plot()

### Model Testing using new data

In [71]:
y_pred = model.predict(X_test_scaled)

#### Interpretations

In [72]:
for applicants in y_pred:
     status = ["Approve" if applicants == 1 else "deny"]
     print(status)

['Approve']
['deny']
['Approve']
['Approve']
['Approve']
['deny']
['Approve']
['deny']
['Approve']
['Approve']
['Approve']
['deny']
['Approve']
['deny']
['Approve']
['deny']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['deny']
['deny']
['Approve']
['Approve']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['Approve']
['deny']
['Approve']
['deny']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['Approve']
['deny']
['Approve']
['deny']
['Approve']
['deny']
['Approve']
['deny']
['deny']
['deny']
['Approve']
['Approve']
['deny']
['deny']
['deny']
['deny']
['Approve']
['Approve']
['deny']
['Approve']
['deny']
['Approve']
['Approve']
['Approve']
['Approve']
['deny']
['Approve']
['deny']
['deny']
['Approve']
['Approve']
['deny']
['Approve']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['deny']
['Approve']
['deny']
['deny']
['deny']
['Approve']
['Approve']
['Approve']
['deny']
['deny']
['deny']
['deny']
['deny']
['Approve']
['deny']
['Approve']
['deny']
['Approve']
['deny']
['deny']
['Approve']
['deny']
['Approve']
['deny']
['deny']
['Approve']
['deny']
['Approve']
['Approve']
['deny']
['Approve']
['Approve']
['deny']
['Approve']
['Approve']
['deny']
['deny']
['deny']
['Approve']
['deny']
['Approve']
['deny']
['deny']
['deny']
['deny']

#### Performance Evaluation on new data

In [73]:
accuracy = accuracy_score(y_test, y_pred)

print(f"accuracy : {accuracy:.2f}")

accuracy : 0.86

In [74]:
precision = precision_score(y_test, y_pred)
print(f"precision : {precision:.2f}")

precision : 0.86

In [75]:
recall = recall_score(y_test, y_pred)

print(f"recall : {recall:.2f}")

recall : 0.84

In [76]:
f1_score = f1_score(y_test, y_pred)

print(f"f1_score : {f1_score:.2f}")

TypeError: 'float' object is not callable

In [77]:
roc_auc = roc_auc_score(y_test, y_pred)

print(f"roc_auc : {roc_auc:.2f}")

roc_auc : 0.85

In [78]:
cm = confusion_matrix(y_test, y_pred)
matrix = ConfusionMatrixDisplay(cm, display_labels = model.classes_ )
matrix.plot()

In [79]:
import streamlit as st
import joblib

In [80]:
joblib.dump(model, "CreditApproval.pkl")

['CreditApproval.pkl']

In [81]:
X.max()

A1       1
A2     251
A3     161
A4       2
A5       2
A6      13
A7       8
A8      94
A9       1
A10      1
A11      8
A12      1
A13      2
A14    126
A15    179
dtype: int64